import { BiCheck, BiLocationPlus, BiSearch } from "react-icons/bi"
import { CiLocationOn } from "react-icons/ci"

export const form_one = {
    name: 'location',
    placeholder: 'city,area...',
    id: "location",
    formType: 'input',
    type: 'text',
    header: 'Location',
    icon: <CiLocationOn size={20} color='black' className='cursor-pointer' />
}

export const form_two = {
    name: 'position',
    placeholder: 'job title, position',
    id: "position",
    formType: 'input',
    type: 'text',
    header: 'Roles',
    icon: <BiSearch size={20} color='black' className='cursor-pointer' />
}

export const form_three = [{
    name: 'name',
    placeholder: 'e.g John doe',
    id: "name",
    formType: 'input',
    type: 'text',
    header: 'Name',
    icon: <BiCheck size={20} color='black' className='cursor-pointer' />
}, {
    name: 'phone',
    placeholder: 'e.g 08022287813',
    id: "phone",
    formType: 'input',
    type: 'text',
    header: 'Phone',
    icon: <BiCheck size={20} color='black' className='cursor-pointer' />
}]

export const Locations = {
    "Lagos": ["Ikeja", "Yaba", "Lekki", "Victoria Island", "Ajah", "Surulere", "Ikoyi", "Agege", "Mushin", "Ikorodu", "Maryland", "Festac", "Oshodi", "Ojota", "Badagry", "Ogba"],
    "Abuja": ["Garki", "Wuse", "Maitama", "Asokoro", "Utako", "Gwarinpa", "Lokogoma", "Lugbe", "Karu", "Jabi", "Kubwa", "Nyanya"],
    "Port Harcourt": ["GRA", "D-Line", "Trans-Amadi", "Rumuola", "Rumuokoro", "Mgbuoba", "Elekahia", "Obio-Akpor", "Oyigbo", "Choba"],
    "Ibadan": ["Bodija", "Mokola", "Dugbe", "Jericho", "Ring Road", "Challenge", "Eleyele", "UI", "Apata", "Iwo Road"],
    "Kano": ["Tarauni", "Nassarawa", "Sabon Gari", "Fagge", "Bompai", "Kofar Ruwa", "Kumbotso", "Gidan Murtala"],
    "Enugu": ["Independence Layout", "New Haven", "Achara Layout", "GRA", "Coal Camp", "Abakpa", "Thinkers Corner"],
    "Benin City": ["Uselu", "Ikpoba Hill", "GRA", "Ugbowo", "Oredo", "New Benin", "Sapele Road"]
};

export const Positions = [
    {
        "id": "91995299-d19e-404e-b838-027f61d69c68",
        "title": "Bill and Account Collector",
        "description": "Id rerum aperiam laborum nisi ut quam dolor. Est deleniti voluptatibus dolorem sint quasi. Similique recusandae placeat rerum aperiam sed distinctio.",
        "company": "Toy, Barrows and Erdman",
        "location": "Gingoog, Grenada",
        "salary_from": 54250,
        "salary_to": 98791,
        "employment_type": "In-house Developer for Non-Tech Company",
        "application_deadline": "Thu, 04/03/1980",
        "qualifications": "[\"Expert in JavaScript\",\"Expert in Java\",\"4+ years in C++\",\"5 years in PHP\"]",
        "contact": "555-108-602",
        "job_category": "Back-end Developer",
        "is_remote_work": 0,
        "number_of_opening": 4,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "34abe66e-b963-41e9-a881-f0cf35afcf1b",
        "title": "Chemical Engineer",
        "description": "Deserunt hic sed et autem nostrum qui debitis. Vitae deserunt voluptas magnam tenetur ut aut voluptatum vel. Eos amet odit sit natus.",
        "company": "Durgan-Wilkinson",
        "location": "Marawi, Canada",
        "salary_from": 54992,
        "salary_to": 110251,
        "employment_type": "Co-founder/Technical Partner",
        "application_deadline": "Fri, 07/31/1992",
        "qualifications": "[\"3+ years in Python\",\"5 years in PHP\",\"Solid understanding of AWS\",\"Skilled in GraphQL\"]",
        "contact": "724-031-191",
        "job_category": "Database Administrator",
        "is_remote_work": 1,
        "number_of_opening": 2,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "83a58f5a-0691-477a-a033-243e314721d7",
        "title": "Physician Assistant",
        "description": "Sint assumenda ut tempora qui. Vel nesciunt atque enim commodi alias vero. Quis ipsam asperiores consequatur iusto et.",
        "company": "Johnson-Orn",
        "location": "Bislig, Indonesia",
        "salary_from": 52132,
        "salary_to": 101300,
        "employment_type": "Co-founder/Technical Partner",
        "application_deadline": "Sun, 01/07/1996",
        "qualifications": "[\"Master of TypeScript\",\"Solid understanding of AWS\",\"Expert in Docker\",\"Proficient in MongoDB\"]",
        "contact": "222-711-567",
        "job_category": "Front-end Developer",
        "is_remote_work": 1,
        "number_of_opening": 3,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "b4822fcc-5df8-46ac-8d87-d03d4e2980f3",
        "title": "Building Cleaning Worker",
        "description": "Ea voluptate vitae adipisci. Qui at autem quas est quis et quaerat.",
        "company": "Marquardt-Romaguera",
        "location": "Danao, Malawi",
        "salary_from": 62629,
        "salary_to": 106846,
        "employment_type": "Contract Developer",
        "application_deadline": "Tue, 06/25/1996",
        "qualifications": "[\"Skilled in React\",\"Expert in Java\",\"Proficient in MongoDB\",\"Skilled in GraphQL\"]",
        "contact": "696-424-280",
        "job_category": "QA Engineer",
        "is_remote_work": 1,
        "number_of_opening": 4,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "1f62b3e7-628f-4b99-9b35-806cea1f1019",
        "title": "Stationary Engineer OR Boiler Operator",
        "description": "Esse repudiandae eos ipsum fugit rerum. Ut non tempora eos sit magni reprehenderit. Voluptas ut quia quaerat deleniti. Provident voluptatum commodi voluptas illo.",
        "company": "Stanton-O'Hara",
        "location": "Gapan, Comoros",
        "salary_from": 61515,
        "salary_to": 109264,
        "employment_type": "Co-founder/Technical Partner",
        "application_deadline": "Sat, 04/17/1971",
        "qualifications": "[\"Expert in JavaScript\",\"Proficient in Kotlin\",\"Solid understanding of AWS\",\"Proficient in MongoDB\"]",
        "contact": "969-860-302",
        "job_category": "Full-stack Developer",
        "is_remote_work": 1,
        "number_of_opening": 10,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "e61ebe60-4f6c-469a-8c9e-9838ff044a4d",
        "title": "Watch Repairer",
        "description": "Eaque voluptatum sed dolore eligendi nam voluptatem aperiam. Recusandae modi id qui distinctio repellat quibusdam. Ea facilis voluptas fugit optio numquam non.",
        "company": "Heller, Farrell and Volkman",
        "location": "Canlaon, Sudan",
        "salary_from": 59579,
        "salary_to": 94297,
        "employment_type": "Intern Developer",
        "application_deadline": "Thu, 05/12/1988",
        "qualifications": "[\"Proficient in SQL\",\"Skilled in React\",\"Skilled in GraphQL\",\"2 years in Vue.js\"]",
        "contact": "976-645-686",
        "job_category": "QA Engineer",
        "is_remote_work": 0,
        "number_of_opening": 8,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "8910fd8c-a1b3-430a-8e33-ffed84f5e5d9",
        "title": "Loan Officer",
        "description": "Doloremque nihil sit sapiente. Aspernatur et nam sint. Sed distinctio itaque molestias reprehenderit.",
        "company": "Collier, Connelly and Williamson",
        "location": "Lapu-Lapu, Wallis and Futuna",
        "salary_from": 74028,
        "salary_to": 102220,
        "employment_type": "Temporary Developer",
        "application_deadline": "Mon, 10/26/2015",
        "qualifications": "[\"Proficient in SQL\",\"2 years of Git experience\",\"Expert in Java\",\"2+ years in Ruby\"]",
        "contact": "348-630-430",
        "job_category": "DevOps Engineer",
        "is_remote_work": 1,
        "number_of_opening": 6,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "65e754c0-1964-49b3-a9cb-f7e2347acc54",
        "title": "Stationary Engineer OR Boiler Operator",
        "description": "Consequatur voluptatem et vitae. Dolor placeat neque non neque impedit officia.",
        "company": "Pouros-Volkman",
        "location": "Calamba, Anguilla",
        "salary_from": 66033,
        "salary_to": 96469,
        "employment_type": "Freelance Developer",
        "application_deadline": "Tue, 02/19/1991",
        "qualifications": "[\"3+ years in Python\",\"Expert in Java\",\"5 years in PHP\",\"Skilled in GraphQL\"]",
        "contact": "538-734-745",
        "job_category": "Security Engineer",
        "is_remote_work": 0,
        "number_of_opening": 4,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "4e5f2656-db65-49a9-b409-c0eb76b40ea1",
        "title": "Military Officer",
        "description": "Quibusdam nulla sapiente veniam excepturi provident aut. Qui explicabo sunt consequatur odio odio rerum quo et. Dolores quibusdam voluptatibus quia tempore.",
        "company": "Wolf-Thompson",
        "location": "Taguig, Nigeria",
        "salary_from": 68616,
        "salary_to": 118078,
        "employment_type": "Intern Developer",
        "application_deadline": "Fri, 05/29/2020",
        "qualifications": "[\"2 years of Git experience\",\"Skilled in React\",\"Proficient in MongoDB\",\"Skilled in GraphQL\"]",
        "contact": "317-416-142",
        "job_category": "Front-end Developer",
        "is_remote_work": 0,
        "number_of_opening": 8,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "255a91fb-8794-4c32-8013-d0c27d7073aa",
        "title": "Payroll Clerk",
        "description": "Cumque molestias possimus sit quam aut aliquid. Commodi in quia tempore consectetur. Tenetur nemo reiciendis quae neque itaque. Est voluptatem nemo non est.",
        "company": "Balistreri, Weber and Kuhlman",
        "location": "Meycauayan, Sudan",
        "salary_from": 63846,
        "salary_to": 93481,
        "employment_type": "Co-founder/Technical Partner",
        "application_deadline": "Fri, 09/09/1988",
        "qualifications": "[\"Advanced HTML\\/CSS\",\"Expert in Java\",\"Solid understanding of AWS\",\"Skilled in GraphQL\"]",
        "contact": "599-545-485",
        "job_category": "Database Administrator",
        "is_remote_work": 1,
        "number_of_opening": 5,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "d8eb31dd-3b50-4a23-afd9-fbe819fef166",
        "title": "Drilling and Boring Machine Tool Setter",
        "description": "Alias sequi nisi minus. Quod iure est officiis excepturi exercitationem.",
        "company": "Skiles-Bartoletti",
        "location": "Oroquieta, Monaco",
        "salary_from": 64781,
        "salary_to": 83465,
        "employment_type": "In-house Developer for Non-Tech Company",
        "application_deadline": "Tue, 05/13/1975",
        "qualifications": "[\"3 years in Node.js\",\"Master of TypeScript\",\"3+ years in Angular\",\"Skilled in GraphQL\"]",
        "contact": "569-794-037",
        "job_category": "Back-end Developer",
        "is_remote_work": 0,
        "number_of_opening": 5,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "93f66d68-502f-4517-a7f3-2f77783e414e",
        "title": "Aircraft Engine Specialist",
        "description": "Magnam ab et dicta voluptates dolor. Error laudantium in qui nulla beatae. Sunt magnam est ipsa occaecati recusandae maxime.",
        "company": "Orn, Connelly and Muller",
        "location": "Marawi, El Salvador",
        "salary_from": 51684,
        "salary_to": 83707,
        "employment_type": "Contract Developer",
        "application_deadline": "Tue, 04/11/2023",
        "qualifications": "[\"Master of TypeScript\",\"Solid understanding of AWS\",\"3+ years in Angular\",\"Proficient in MongoDB\"]",
        "contact": "370-831-244",
        "job_category": "UI/UX Designer",
        "is_remote_work": 1,
        "number_of_opening": 9,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "574a73bb-f4f1-473b-9cc5-dd15fb80dd57",
        "title": "Orthotist OR Prosthetist",
        "description": "Qui explicabo dolores quis cumque sed. Consectetur sunt debitis id quia laboriosam alias suscipit. Perferendis ut tenetur magni hic ea cumque aut. Aliquid vero perspiciatis placeat et.",
        "company": "Schaefer PLC",
        "location": "Palayan, Cuba",
        "salary_from": 65696,
        "salary_to": 98165,
        "employment_type": "Remote Developer",
        "application_deadline": "Sun, 09/09/1973",
        "qualifications": "[\"Proficient in SQL\",\"Expert in Java\",\"Solid understanding of AWS\",\"Expert in Docker\"]",
        "contact": "275-036-200",
        "job_category": "Full-stack Developer",
        "is_remote_work": 1,
        "number_of_opening": 8,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "bf7b5592-3619-449c-83a6-7208d4d89ff4",
        "title": "Supervisor Correctional Officer",
        "description": "Rerum veniam harum sapiente nostrum et eligendi. Temporibus laboriosam dignissimos qui eos enim et voluptate rerum. Molestiae eius laborum et doloremque repudiandae neque. Autem explicabo in asperiores illo.",
        "company": "Jenkins PLC",
        "location": "Marikina, Cuba",
        "salary_from": 73268,
        "salary_to": 105321,
        "employment_type": "Co-founder/Technical Partner",
        "application_deadline": "Mon, 10/05/1992",
        "qualifications": "[\"Advanced HTML\\/CSS\",\"4+ years in C++\",\"Master of TypeScript\",\"Proficient in Kotlin\"]",
        "contact": "303-679-261",
        "job_category": "UI/UX Designer",
        "is_remote_work": 1,
        "number_of_opening": 1,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "0a69c384-3a9e-4842-b406-165ee7c649f0",
        "title": "Maintenance Equipment Operator",
        "description": "Illo et minus saepe. Illum facilis cumque labore veritatis at. Non consequatur voluptas ipsam cupiditate.",
        "company": "Botsford, Erdman and Cronin",
        "location": "Lipa, Albania",
        "salary_from": 67098,
        "salary_to": 83271,
        "employment_type": "Contract Developer",
        "application_deadline": "Sat, 05/24/2014",
        "qualifications": "[\"Advanced HTML\\/CSS\",\"Proficient in SQL\",\"4+ years in C++\",\"Skilled in GraphQL\"]",
        "contact": "072-005-960",
        "job_category": "Mobile App Developer",
        "is_remote_work": 0,
        "number_of_opening": 3,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "009bbce7-8e4c-4586-8a1a-b297cb711245",
        "title": "Drafter",
        "description": "Est autem quo et expedita voluptatibus. Et qui quaerat suscipit aut fugit voluptatem sunt omnis. Rem excepturi nesciunt ut qui magnam.",
        "company": "Mosciski-Predovic",
        "location": "Iligan, Seychelles",
        "salary_from": 70187,
        "salary_to": 106000,
        "employment_type": "Remote Developer",
        "application_deadline": "Thu, 12/14/2000",
        "qualifications": "[\"Expert in JavaScript\",\"Advanced HTML\\/CSS\",\"5 years in PHP\",\"Expert in Docker\"]",
        "contact": "986-298-557",
        "job_category": "Security Engineer",
        "is_remote_work": 1,
        "number_of_opening": 2,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "feb4368b-f629-49bb-8af5-9bc717ed4363",
        "title": "Air Traffic Controller",
        "description": "Et aliquam voluptatem laborum minima id. Ullam commodi cupiditate perferendis. Iste est ut autem ad. Necessitatibus ut corporis ut eum.",
        "company": "Kautzer-Jacobi",
        "location": "Imus, Benin",
        "salary_from": 72003,
        "salary_to": 89054,
        "employment_type": "Remote Developer",
        "application_deadline": "Sat, 08/18/2012",
        "qualifications": "[\"3+ years in Python\",\"4+ years in C++\",\"Expert in Docker\",\"Skilled in GraphQL\"]",
        "contact": "948-177-289",
        "job_category": "Full-stack Developer",
        "is_remote_work": 0,
        "number_of_opening": 7,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "c7b3e1d0-f95d-45b0-a7d2-8c2398ede37a",
        "title": "Prosthodontist",
        "description": "Dolor atque magni aut possimus. Minima cum porro ut nobis accusamus quam. Sapiente commodi corrupti rem sed debitis rerum et. Eum ex aut et et autem sed qui.",
        "company": "McLaughlin, Gutmann and Medhurst",
        "location": "Trece Martires, Angola",
        "salary_from": 74725,
        "salary_to": 85063,
        "employment_type": "Consultant",
        "application_deadline": "Mon, 05/02/2016",
        "qualifications": "[\"Advanced HTML\\/CSS\",\"2 years of Git experience\",\"3 years in Node.js\",\"Solid understanding of AWS\"]",
        "contact": "610-591-607",
        "job_category": "Security Engineer",
        "is_remote_work": 1,
        "number_of_opening": 1,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "234d26f6-8ed5-411d-ac90-3bd595121551",
        "title": "Nuclear Technician",
        "description": "Eum itaque omnis debitis eaque. Repellat voluptatem ut beatae vero. Neque eveniet omnis tempora eos esse quas ab.",
        "company": "Kirlin-Muller",
        "location": "Malolos, Japan",
        "salary_from": 59665,
        "salary_to": 115725,
        "employment_type": "Intern Developer",
        "application_deadline": "Sat, 11/12/2011",
        "qualifications": "[\"3+ years in Python\",\"3 years in Node.js\",\"Advanced in Swift\",\"Expert in Docker\"]",
        "contact": "625-551-794",
        "job_category": "Security Engineer",
        "is_remote_work": 0,
        "number_of_opening": 5,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "1801e8c4-b625-4629-9a74-71020aa764c9",
        "title": "Locomotive Firer",
        "description": "Sequi soluta dicta est eius voluptate reprehenderit. Quis distinctio fuga asperiores aut. Ratione delectus qui ea. Cupiditate asperiores ipsam molestiae enim nihil voluptatem sint.",
        "company": "Waters Inc",
        "location": "San Juan, French Southern Territories",
        "salary_from": 77833,
        "salary_to": 103904,
        "employment_type": "Consultant",
        "application_deadline": "Sun, 04/13/1997",
        "qualifications": "[\"4+ years in C++\",\"5 years in PHP\",\"Expert in Docker\",\"Skilled in GraphQL\"]",
        "contact": "452-141-875",
        "job_category": "Security Engineer",
        "is_remote_work": 0,
        "number_of_opening": 3,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "1217775c-6b03-4965-a459-13a2efa67041",
        "title": "Dental Hygienist",
        "description": "Sunt dolorem asperiores numquam magni. Cupiditate voluptas et et dolor. Officia molestiae impedit enim vel aspernatur sit id. At laborum quo aut quia sit reiciendis.",
        "company": "Kutch-Schiller",
        "location": "Lucena, Gibraltar",
        "salary_from": 75586,
        "salary_to": 99840,
        "employment_type": "Part-time Developer",
        "application_deadline": "Sun, 12/31/2006",
        "qualifications": "[\"Advanced in Swift\",\"Proficient in Kotlin\",\"5 years in PHP\",\"2 years in Vue.js\"]",
        "contact": "718-448-649",
        "job_category": "Mobile App Developer",
        "is_remote_work": 0,
        "number_of_opening": 4,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "a077ccc8-2320-4aa2-9778-e8e4cc9aede7",
        "title": "Chemical Equipment Tender",
        "description": "Voluptatem cumque vel ducimus modi omnis animi. Ipsam repellat molestias molestiae consequatur debitis et. Quia vero voluptatum aut tempore natus. Et similique recusandae est corporis.",
        "company": "Cassin, Swaniawski and Kiehn",
        "location": "Ozamiz, Jersey",
        "salary_from": 53042,
        "salary_to": 88698,
        "employment_type": "Co-founder/Technical Partner",
        "application_deadline": "Thu, 03/21/1991",
        "qualifications": "[\"Expert in JavaScript\",\"4+ years in C++\",\"Master of TypeScript\",\"2 years in Vue.js\"]",
        "contact": "311-634-761",
        "job_category": "Front-end Developer",
        "is_remote_work": 1,
        "number_of_opening": 1,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "17746a87-be03-440a-b754-6b97822de4a7",
        "title": "Composer",
        "description": "Et voluptate vel nobis voluptas ut quia neque minus. Sint et modi quia voluptatem.",
        "company": "Reilly Inc",
        "location": "Bacolod, Equatorial Guinea",
        "salary_from": 78475,
        "salary_to": 91043,
        "employment_type": "Intern Developer",
        "application_deadline": "Sun, 11/21/2021",
        "qualifications": "[\"Advanced HTML\\/CSS\",\"3 years in Node.js\",\"2+ years in Ruby\",\"2 years in Vue.js\"]",
        "contact": "961-175-676",
        "job_category": "QA Engineer",
        "is_remote_work": 1,
        "number_of_opening": 9,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "b59ec44d-fee7-4c41-b4ec-0697f92f4758",
        "title": "Lodging Manager",
        "description": "Consequuntur nihil neque laudantium sed quos. Vero velit quae reiciendis. Ipsum eum mollitia in ut fugit sunt molestias. Repellendus dolorem iusto veritatis aspernatur.",
        "company": "Wuckert-Dare",
        "location": "Lamitan, French Guiana",
        "salary_from": 71138,
        "salary_to": 112862,
        "employment_type": "Consultant",
        "application_deadline": "Fri, 08/11/2000",
        "qualifications": "[\"3+ years in Python\",\"4+ years in C++\",\"Master of TypeScript\",\"Expert in Docker\"]",
        "contact": "400-306-131",
        "job_category": "Mobile App Developer",
        "is_remote_work": 0,
        "number_of_opening": 9,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "4b7a76ab-6f7a-4a87-81ef-a2c547c1ddae",
        "title": "Sheriff",
        "description": "Tempora eaque at harum quis. Consectetur voluptatem voluptatem consequatur dolores. Qui nihil ad sint earum.",
        "company": "Wilkinson and Sons",
        "location": "Angeles, Sierra Leone",
        "salary_from": 65118,
        "salary_to": 87776,
        "employment_type": "Consultant",
        "application_deadline": "Thu, 07/02/1992",
        "qualifications": "[\"Proficient in SQL\",\"Expert in Java\",\"Master of TypeScript\",\"Expert in Docker\"]",
        "contact": "978-720-405",
        "job_category": "QA Engineer",
        "is_remote_work": 0,
        "number_of_opening": 1,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "d25d5df9-0bdc-4c5a-a554-fd6ed7470001",
        "title": "Tax Preparer",
        "description": "Ipsam assumenda libero harum accusantium veniam. Quo cum maiores voluptate voluptas. Consequuntur vitae a eos aut veritatis voluptas dicta deleniti.",
        "company": "Bosco Inc",
        "location": "Tarlac City, Slovakia (Slovak Republic)",
        "salary_from": 53686,
        "salary_to": 110829,
        "employment_type": "Intern Developer",
        "application_deadline": "Wed, 10/28/1992",
        "qualifications": "[\"Expert in JavaScript\",\"Master of TypeScript\",\"5 years in PHP\",\"Expert in Docker\"]",
        "contact": "090-971-568",
        "job_category": "Security Engineer",
        "is_remote_work": 1,
        "number_of_opening": 9,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    },
    {
        "id": "ce79bda6-30c8-40f1-ab03-954386a01794",
        "title": "Platemaker",
        "description": "Ut exercitationem praesentium voluptas atque minus qui. Nihil consequatur qui velit dicta nemo nobis quia rem. Expedita ab natus dolores.",
        "company": "Hand-Jenkins",
        "location": "San Pedro, Macedonia",
        "salary_from": 77924,
        "salary_to": 109606,
        "employment_type": "Freelance Developer",
        "application_deadline": "Wed, 03/17/1993",
        "qualifications": "[\"Expert in JavaScript\",\"3+ years in Angular\",\"Expert in Docker\",\"Proficient in MongoDB\"]",
        "contact": "323-555-128",
        "job_category": "Back-end Developer",
        "is_remote_work": 0,
        "number_of_opening": 8,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
    }]